import React, { useState } from 'react';

export default function VerifyPage() {
  const [content, setContent] = useState('');
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleVerify = async () => {
    if (!content.trim()) return;
    setLoading(true);
    setResult(null);
    try {
      const response = await fetch('http://localhost:8000/api/verify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ content: content })
      });
      const data = await response.json();
      setResult(data);
    } catch (err) {
      console.error(err);
      alert('Cannot connect to backend verification endpoint. Make sure your backend server is running on port 8000.');
    } finally {
      setLoading(false);
    }
  };

  const handleFileUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => setContent(event.target.result);
    reader.readAsText(file);
  };

  return (
    <div className="max-w-4xl mx-auto p-6 space-y-6">
      <div className="border-b border-gray-200 dark:border-gray-800 pb-4">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
          🛡️ Content Provenance & Verification Portal
        </h1>
        <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
          Verify whether an advisory, briefing, or post is Authentic or Tampered using SHA-256 cryptographic ledger matching.
        </p>
      </div>

      <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl p-5 shadow-sm space-y-4">
        <div className="flex justify-between items-center">
          <label className="text-sm font-semibold text-gray-700 dark:text-gray-300">
            Paste Content or Upload Deliverable:
          </label>
          <input
            type="file"
            accept=".txt,.json,.md"
            onChange={handleFileUpload}
            className="text-xs text-gray-500 file:mr-2 file:py-1 file:px-3 file:rounded-md file:border-0 file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100 cursor-pointer"
          />
        </div>

        <textarea
          rows={6}
          value={content}
          onChange={(e) => setContent(e.target.value)}
          placeholder="Paste security advisory text, briefing notes, or JSON output here..."
          className="w-full p-3 text-sm bg-gray-50 dark:bg-gray-950 border border-gray-300 dark:border-gray-800 rounded-lg font-mono focus:ring-2 focus:ring-indigo-500"
        />

        <button
          onClick={handleVerify}
          disabled={loading || !content.trim()}
          className="w-full py-2.5 px-4 bg-indigo-600 hover:bg-indigo-700 text-white font-medium rounded-lg transition-colors flex items-center justify-center gap-2 shadow-sm disabled:opacity-50"
        >
          {loading ? 'Recomputing SHA-256 Hash...' : '🔍 Check Cryptographic Authenticity'}
        </button>
      </div>

      {result && (
        <div className={`p-6 rounded-xl border ${
          result.is_authentic 
            ? 'bg-emerald-50 dark:bg-emerald-950/30 border-emerald-300 dark:border-emerald-800' 
            : 'bg-rose-50 dark:bg-rose-950/30 border-rose-300 dark:border-rose-800'
        } shadow-sm space-y-4`}>
          
          <div className="flex items-center gap-3">
            <span className="text-3xl">{result.is_authentic ? '✅' : '❌'}</span>
            <div>
              <h2 className={`text-xl font-bold ${result.is_authentic ? 'text-emerald-800 dark:text-emerald-300' : 'text-rose-800 dark:text-rose-300'}`}>
                {result.is_authentic ? 'AUTHENTIC DELIVERABLE VERIFIED' : 'TAMPERED OR UNVERIFIED CONTENT'}
              </h2>
              <p className="text-xs text-gray-600 dark:text-gray-400">
                {result.is_authentic 
                  ? 'Cryptographic hash match confirmed in the immutable Provenance Ledger.'
                  : 'Warning: Hash mismatch! Content has been altered or was not generated by this system.'}
              </p>
            </div>
          </div>

          <div className="bg-white/80 dark:bg-gray-900/80 rounded-lg p-3 border border-gray-200 dark:border-gray-800 font-mono text-xs space-y-1">
            <div className="text-gray-500">Computed SHA-256 Fingerprint:</div>
            <div className="text-indigo-600 dark:text-indigo-400 break-all select-all font-semibold">
              {result.computed_hash}
            </div>
          </div>

          {result.is_authentic && result.matched_block && (
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs pt-2">
              <div className="bg-emerald-100/50 dark:bg-emerald-900/30 p-2.5 rounded-md">
                <div className="text-gray-500">Ledger Block:</div>
                <div className="font-bold text-gray-900 dark:text-white">#{result.matched_block.block_index}</div>
              </div>
              <div className="bg-emerald-100/50 dark:bg-emerald-900/30 p-2.5 rounded-md">
                <div className="text-gray-500">Timestamp:</div>
                <div className="font-bold text-gray-900 dark:text-white">
                  {new Date(result.matched_block.timestamp).toLocaleTimeString()}
                </div>
              </div>
              <div className="bg-emerald-100/50 dark:bg-emerald-900/30 p-2.5 rounded-md">
                <div className="text-gray-500">Operator:</div>
                <div className="font-bold text-gray-900 dark:text-white">{result.matched_block.operator}</div>
              </div>
              <div className="bg-emerald-100/50 dark:bg-emerald-900/30 p-2.5 rounded-md">
                <div className="text-gray-500">Parameters:</div>
                <div className="font-bold text-gray-900 dark:text-white">
                  {result.matched_block.parameters?.tone || 'Verified'}
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
